// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import BstabsController from "./bstabs_controller"
application.register("bstabs", BstabsController)

import SelectController from "@swobspace/stimulus-slim-select"
application.register("select", SelectController)

// -- polymorphic for wobauth
import PolymorphicSelectController from "@swobspace/stimulus-polymorphic-select"
application.register("polymorphic-select", PolymorphicSelectController)
