// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BstabsController from "./bstabs_controller.js"
application.register("bstabs", BstabsController)

import DatatablesController from "./datatables_controller.js"
application.register("datatables", DatatablesController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ImagezoomController from "./imagezoom_controller.js"
application.register("imagezoom", ImagezoomController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)

import ToastController from "./toast_controller.js"
application.register("toast", ToastController)

import ToggleController from "./toggle_controller.js"
application.register("toggle", ToggleController)

import SelectController from "@swobspace/stimulus-slim-select"
application.register("select", SelectController)

// -- polymorphic for wobauth
import PolymorphicSelectController from "@swobspace/stimulus-polymorphic-select"
application.register("polymorphic-select", PolymorphicSelectController)

