# docker-compose.dev.yml

x-base: &base
  build:
    context: .
    dockerfile: .docker/Dockerfile.dev
  stdin_open: true
  tty: true
  volumes:
    - .:/app:z,cached
  depends_on:
    - redis
#     - postgres
  env_file:
    - .env.development.local

services:
  app:
    <<: *base
    command: bin/dev
    restart: on-failure
    ports:
      - "3000:3000"

  worker:
    <<: *base
    command: good_job start
    restart: on-failure

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
