= Modeling mirco
:imagesdir: ../images

== Overall Picture

image::models.svg[]

== Home controller

[source,ruby]
----
bin/rails g controller Home index \
  --no-stylesheets --no-javascripts --no-helper
----

== model Server

[source,ruby]
----
bin/rails g scaffold Server \
  location:belongs_to \
  host:belongs_to \
  name:string uid:string:index description:text \
  api_url:string api_user:string api_password_ciphertext:text \
  api_user_has_full_access:boolean \
  api_verify_ssl:boolean \
  properties:jsonb \
  last_channel_update:timestamp \
  last_check:timestamp last_check_ok:timestamp \
  manual_update:boolean \
  --no-stylesheets --no-javascripts --no-helper

----
// bin/rails g migration AddVerifySslToServer api_verify_ssl:boolean
// bin/rails g migration AddLastChannelUpdateToServer \
//  last_channel_update:timestamp
// bin/rails g migration AddLastCheckToServer \
//  last_check:timestamp last_check_ok:timestamp
// bin/rails g migration AddLocationToServer location:belongs_to
// bin/rails g migration RemoveLocationFromServer


== model Channel

[source,ruby]
----
bin/rails g scaffold Channel \
  server:belongs_to \
  uid:string:index \
  properties:jsonb \
  enabled:boolean \
  --no-stylesheets --no-javascripts --no-helper
----

== Model ChannelStatistic

[source,ruby]
----
bin/rails g scaffold ChannelStatistic \
  server:belongs_to \
  channel:belongs_to \
  meta_data_id:integer \
  server_uid:string:index \
  channel_uid:string:index \
  name:string state:string status_type:string \
  received:integer \
  sent:integer \
  error:integer \
  filtered:integer \
  queued:integer \
  condition:string:index \
  last_condition_change:timestamp \
  --no-stylesheets --no-javascripts --no-helper
----
// bin/rails g migration AddMetaDataIdToChannelStatistic meta_data_id:integer
// bin/rails g migration AddStatusesFieldsToChannelStatistic \
//   name:string state:string status_type:string
// bin/rails g migration AddConditionToChannelStatistic \
//   condition:string:index last_condition_change:timestamp

== Model ChannelCounter

include::partial$scaffold-channel_counter.adoc[]

see also: xref:timescale.adoc[]

.Generate Controller with action :index
[source,ruby]
----
bin/rails g controller channel_counters index \
  --no-stylesheets --no-javascripts --no-helper
----

== Model Alert

[source,ruby]
----
bin/rails g scaffold Alert \
  server:belongs_to \
  channel:belongs_to \
  channel_statistic:belongs_to \
  type:string:index \
  message:text \
  --no-stylesheets --no-javascripts --no-helper
----
// bin/rails g migration AddChannelStatisticIdToAlert \
//   channel_statistic:belongs_to

[cols="1,3"]
|===
|type
a|`alert`, `recovery`
|===

== Model Note

[source,ruby]
----
bin/rails g scaffold Note \
  server:belongs_to \
  channel:belongs_to \
  channel_statistic:belongs_to \
  user:belongs_to \
  type:string:index \
  --no-stylesheets --no-javascripts --no-helper
----
// bin/rails g migration AddChannelStatisticIdToNote \
//   channel_statistic:belongs_to

[cols="1,3"]
|===
|type
a|`acknowledge`, `mail`, `note`
|===

.Install ActionText
[source,ruby]
----
bin/rails action_text:install
----

.app/models/note.rb
[source,ruby]
----
class Note < ApplicationRecord
  has_rich_text :message
end
----

== Model ServerConfiguration

[source,ruby]
----
bin/rails g model ServerConfiguration \
  server:belongs_to \
  comment:string

bin/rails g controller ServerConfiguration index show
----
