= Modeling mirco
:imagesdir: ../images

== Overall Picture

image::models.svg[]

== Home controller

[source,sh]
----
bin/rails g controller Home index \
  --no-stylesheets --no-javascripts --no-helper
----

== model Server

[source,sh]
----
bin/rails g scaffold Server \
  location:belongs_to \
  host:belongs_to \
  name:string uid:string:index description:text \
  api_url:string api_user:string api_password_ciphertext:text \
  api_user_has_full_access:boolean \
  api_verify_ssl:boolean \
  properties:jsonb \
  last_channel_update:timestamp \
  last_check:timestamp last_check_ok:timestamp \
  manual_update:boolean \
  --no-stylesheets --no-javascripts --no-helper

----
// bin/rails g migration AddVerifySslToServer api_verify_ssl:boolean
// bin/rails g migration AddLastChannelUpdateToServer \
//  last_channel_update:timestamp
// bin/rails g migration AddLastCheckToServer \
//  last_check:timestamp last_check_ok:timestamp
// bin/rails g migration AddLocationToServer location:belongs_to
// bin/rails g migration RemoveLocationFromServer


== model Channel

[source,sh]
----
bin/rails g scaffold Channel \
  server:belongs_to \
  uid:string:index \
  properties:jsonb \
  enabled:boolean \
  --no-stylesheets --no-javascripts --no-helper
----

== Model ChannelStatistic

[source,sh]
----
bin/rails g scaffold ChannelStatistic \
  server:belongs_to \
  channel:belongs_to \
  meta_data_id:integer \
  server_uid:string:index \
  channel_uid:string:index \
  name:string state:string status_type:string \
  received:integer \
  sent:integer \
  error:integer \
  filtered:integer \
  queued:integer \
  condition:integer:index \
  last_condition_change:timestamp \
  last_message_received_at:timestamp \
  last_message_sent_at:timestamp \
  last_message_error_at:timestamp \
  --no-stylesheets --no-javascripts --no-helper
----
// bin/rails g migration AddMetaDataIdToChannelStatistic meta_data_id:integer
// bin/rails g migration AddStatusesFieldsToChannelStatistic \
//   name:string state:string status_type:string
// bin/rails g migration AddConditionToChannelStatistic \
//   condition:string:index last_condition_change:timestamp
// bin/rails g migration AddLastMessageAtToChannelStatistic \
//   last_message_received_at:timestamp last_message_sent_at:timestamp \
//   last_message_error_at:timestamp

== Model ChannelCounter

include::partial$scaffold-channel_counter.adoc[]

see also: xref:timescale.adoc[]

.Generate Controller with action :index
[source,sh]
----
bin/rails g controller channel_counters index \
  --no-stylesheets --no-javascripts --no-helper
----

== Model Alert

[source,sh]
----
bin/rails g scaffold Alert \
  server:belongs_to \
  channel:belongs_to \
  channel_statistic:belongs_to \
  type:string:index \
  message:text \
  --no-stylesheets --no-javascripts --no-helper
----
// bin/rails g migration AddChannelStatisticIdToAlert \
//   channel_statistic:belongs_to

[cols="1,3"]
|===
|type
a|`alert`, `recovery`
|===

== Model Note

[source,sh]
----
bin/rails g scaffold Note \
  server:belongs_to \
  channel:belongs_to \
  channel_statistic:belongs_to \
  user:belongs_to \
  type:string:index \
  --no-stylesheets --no-javascripts --no-helper
----
// bin/rails g migration AddChannelStatisticIdToNote \
//   channel_statistic:belongs_to

[cols="1,3"]
|===
|type
a|`acknowledge`, `mail`, `note`
|===

.Install ActionText
[source,sh]
----
bin/rails action_text:install
----

.app/models/note.rb
[source,sh]
----
class Note < ApplicationRecord
  has_rich_text :message
end
----

== Model ServerConfiguration

[source,sh]
----
bin/rails g model ServerConfiguration \
  server:belongs_to \
  comment:string

bin/rails g controller ServerConfiguration index show
----

== Model EscalationLevel
[source,sh]
----
bin/rails g scaffold EscalationLevel \
  escalatable:references{polymorphic} \
  attrib:string:index \
  min_critical:integer \
  min_warning:integer \
  max_warning:integer \
  max_critical:integer \
  notification_group:belongs_to \
  show_on_dashboard:boolean:index \
  --no-stylesheets --no-javascripts --no-helper
----

== Model EscalationTime
[source,sh]
----
bin/rails g scaffold EscalationTime \
  escalation_level:belongs_to \
  start_time:string{limit:5} \
  end_time:string{limit:5} \
  weekdays:integer{array} \
  --no-stylesheets --no-javascripts --no-helper --no-decorator
----

== Model NotificationGroup
[source,sh]
----
bin/rails g scaffold NotificationGroup \
  name:string:index \
  --no-stylesheets --no-javascripts --no-helper --no-decorator
----

[source,sh]
----
bin/rails g migration CreateJoinTableNotificationGroupWobauthUser \
  notification_group wobauth_user
----

[source,ruby]
----
def change
  create_join_table :notification_group, :wobauth_user do |t|
    t.index [:notification_group_id, :wobauth_user_id], name: 'idx_notificationgroup_user'
    t.index [:wobauth_user_id, :notification_group_id], name: 'idx_user_notificationgroup'
  end
end
----

== Model ChannelStatisticGroup
[source,sh]
----
bin/rails g scaffold ChannelStatisticGroup \
  name:string \
  --no-stylesheets --no-javascripts --no-helper --no-decorator
----

[source,sh]
----
bin/rails g migration CreateJoinTable ChannelStatisticChannelStatisticGroup \
  channel_statistic channel_statistic_group
----

[source,ruby]
----
def change
  create_join_table :channel_statistics, :channel_statistic_groups do |t|
    t.index [:channel_statistic_group_id, :channel_statistic_id], name: 'idx_statisticsgroup_statistic'
    t.index [:channel_statistic_id, :channel_statistic_group_id], name: 'idx_statistic_statisticsgroup'
  end
end
----
