 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/channel_statistics", type: :request do
  
  # ChannelStatistic. As you add validations to ChannelStatistic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ChannelStatistic.create! valid_attributes
      get channel_statistics_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      channel_statistic = ChannelStatistic.create! valid_attributes
      get channel_statistic_url(channel_statistic)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_channel_statistic_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      channel_statistic = ChannelStatistic.create! valid_attributes
      get edit_channel_statistic_url(channel_statistic)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ChannelStatistic" do
        expect {
          post channel_statistics_url, params: { channel_statistic: valid_attributes }
        }.to change(ChannelStatistic, :count).by(1)
      end

      it "redirects to the created channel_statistic" do
        post channel_statistics_url, params: { channel_statistic: valid_attributes }
        expect(response).to redirect_to(channel_statistic_url(ChannelStatistic.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ChannelStatistic" do
        expect {
          post channel_statistics_url, params: { channel_statistic: invalid_attributes }
        }.to change(ChannelStatistic, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post channel_statistics_url, params: { channel_statistic: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested channel_statistic" do
        channel_statistic = ChannelStatistic.create! valid_attributes
        patch channel_statistic_url(channel_statistic), params: { channel_statistic: new_attributes }
        channel_statistic.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the channel_statistic" do
        channel_statistic = ChannelStatistic.create! valid_attributes
        patch channel_statistic_url(channel_statistic), params: { channel_statistic: new_attributes }
        channel_statistic.reload
        expect(response).to redirect_to(channel_statistic_url(channel_statistic))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        channel_statistic = ChannelStatistic.create! valid_attributes
        patch channel_statistic_url(channel_statistic), params: { channel_statistic: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested channel_statistic" do
      channel_statistic = ChannelStatistic.create! valid_attributes
      expect {
        delete channel_statistic_url(channel_statistic)
      }.to change(ChannelStatistic, :count).by(-1)
    end

    it "redirects to the channel_statistics list" do
      channel_statistic = ChannelStatistic.create! valid_attributes
      delete channel_statistic_url(channel_statistic)
      expect(response).to redirect_to(channel_statistics_url)
    end
  end
end
