require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/escalation_levels", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EscalationLevel. As you add validations to EscalationLevel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EscalationLevel.create! valid_attributes
      get escalation_levels_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      escalation_level = EscalationLevel.create! valid_attributes
      get escalation_level_url(escalation_level)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_escalation_level_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      escalation_level = EscalationLevel.create! valid_attributes
      get edit_escalation_level_url(escalation_level)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EscalationLevel" do
        expect {
          post escalation_levels_url, params: { escalation_level: valid_attributes }
        }.to change(EscalationLevel, :count).by(1)
      end

      it "redirects to the created escalation_level" do
        post escalation_levels_url, params: { escalation_level: valid_attributes }
        expect(response).to redirect_to(escalation_level_url(EscalationLevel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EscalationLevel" do
        expect {
          post escalation_levels_url, params: { escalation_level: invalid_attributes }
        }.to change(EscalationLevel, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post escalation_levels_url, params: { escalation_level: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested escalation_level" do
        escalation_level = EscalationLevel.create! valid_attributes
        patch escalation_level_url(escalation_level), params: { escalation_level: new_attributes }
        escalation_level.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the escalation_level" do
        escalation_level = EscalationLevel.create! valid_attributes
        patch escalation_level_url(escalation_level), params: { escalation_level: new_attributes }
        escalation_level.reload
        expect(response).to redirect_to(escalation_level_url(escalation_level))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        escalation_level = EscalationLevel.create! valid_attributes
        patch escalation_level_url(escalation_level), params: { escalation_level: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested escalation_level" do
      escalation_level = EscalationLevel.create! valid_attributes
      expect {
        delete escalation_level_url(escalation_level)
      }.to change(EscalationLevel, :count).by(-1)
    end

    it "redirects to the escalation_levels list" do
      escalation_level = EscalationLevel.create! valid_attributes
      delete escalation_level_url(escalation_level)
      expect(response).to redirect_to(escalation_levels_url)
    end
  end
end
