require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/interface_connectors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # InterfaceConnector. As you add validations to InterfaceConnector, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      InterfaceConnector.create! valid_attributes
      get interface_connectors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      interface_connector = InterfaceConnector.create! valid_attributes
      get interface_connector_url(interface_connector)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_interface_connector_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      interface_connector = InterfaceConnector.create! valid_attributes
      get edit_interface_connector_url(interface_connector)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new InterfaceConnector" do
        expect {
          post interface_connectors_url, params: { interface_connector: valid_attributes }
        }.to change(InterfaceConnector, :count).by(1)
      end

      it "redirects to the created interface_connector" do
        post interface_connectors_url, params: { interface_connector: valid_attributes }
        expect(response).to redirect_to(interface_connector_url(InterfaceConnector.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new InterfaceConnector" do
        expect {
          post interface_connectors_url, params: { interface_connector: invalid_attributes }
        }.to change(InterfaceConnector, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post interface_connectors_url, params: { interface_connector: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested interface_connector" do
        interface_connector = InterfaceConnector.create! valid_attributes
        patch interface_connector_url(interface_connector), params: { interface_connector: new_attributes }
        interface_connector.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the interface_connector" do
        interface_connector = InterfaceConnector.create! valid_attributes
        patch interface_connector_url(interface_connector), params: { interface_connector: new_attributes }
        interface_connector.reload
        expect(response).to redirect_to(interface_connector_url(interface_connector))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        interface_connector = InterfaceConnector.create! valid_attributes
        patch interface_connector_url(interface_connector), params: { interface_connector: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested interface_connector" do
      interface_connector = InterfaceConnector.create! valid_attributes
      expect {
        delete interface_connector_url(interface_connector)
      }.to change(InterfaceConnector, :count).by(-1)
    end

    it "redirects to the interface_connectors list" do
      interface_connector = InterfaceConnector.create! valid_attributes
      delete interface_connector_url(interface_connector)
      expect(response).to redirect_to(interface_connectors_url)
    end
  end
end
