require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/software_interfaces", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SoftwareInterface. As you add validations to SoftwareInterface, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SoftwareInterface.create! valid_attributes
      get software_interfaces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      software_interface = SoftwareInterface.create! valid_attributes
      get software_interface_url(software_interface)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_software_interface_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      software_interface = SoftwareInterface.create! valid_attributes
      get edit_software_interface_url(software_interface)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SoftwareInterface" do
        expect {
          post software_interfaces_url, params: { software_interface: valid_attributes }
        }.to change(SoftwareInterface, :count).by(1)
      end

      it "redirects to the created software_interface" do
        post software_interfaces_url, params: { software_interface: valid_attributes }
        expect(response).to redirect_to(software_interface_url(SoftwareInterface.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SoftwareInterface" do
        expect {
          post software_interfaces_url, params: { software_interface: invalid_attributes }
        }.to change(SoftwareInterface, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post software_interfaces_url, params: { software_interface: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested software_interface" do
        software_interface = SoftwareInterface.create! valid_attributes
        patch software_interface_url(software_interface), params: { software_interface: new_attributes }
        software_interface.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the software_interface" do
        software_interface = SoftwareInterface.create! valid_attributes
        patch software_interface_url(software_interface), params: { software_interface: new_attributes }
        software_interface.reload
        expect(response).to redirect_to(software_interface_url(software_interface))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        software_interface = SoftwareInterface.create! valid_attributes
        patch software_interface_url(software_interface), params: { software_interface: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested software_interface" do
      software_interface = SoftwareInterface.create! valid_attributes
      expect {
        delete software_interface_url(software_interface)
      }.to change(SoftwareInterface, :count).by(-1)
    end

    it "redirects to the software_interfaces list" do
      software_interface = SoftwareInterface.create! valid_attributes
      delete software_interface_url(software_interface)
      expect(response).to redirect_to(software_interfaces_url)
    end
  end
end
