require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/software_groups", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SoftwareGroup. As you add validations to SoftwareGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SoftwareGroup.create! valid_attributes
      get software_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      software_group = SoftwareGroup.create! valid_attributes
      get software_group_url(software_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_software_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      software_group = SoftwareGroup.create! valid_attributes
      get edit_software_group_url(software_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SoftwareGroup" do
        expect {
          post software_groups_url, params: { software_group: valid_attributes }
        }.to change(SoftwareGroup, :count).by(1)
      end

      it "redirects to the created software_group" do
        post software_groups_url, params: { software_group: valid_attributes }
        expect(response).to redirect_to(software_group_url(SoftwareGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SoftwareGroup" do
        expect {
          post software_groups_url, params: { software_group: invalid_attributes }
        }.to change(SoftwareGroup, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post software_groups_url, params: { software_group: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested software_group" do
        software_group = SoftwareGroup.create! valid_attributes
        patch software_group_url(software_group), params: { software_group: new_attributes }
        software_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the software_group" do
        software_group = SoftwareGroup.create! valid_attributes
        patch software_group_url(software_group), params: { software_group: new_attributes }
        software_group.reload
        expect(response).to redirect_to(software_group_url(software_group))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        software_group = SoftwareGroup.create! valid_attributes
        patch software_group_url(software_group), params: { software_group: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested software_group" do
      software_group = SoftwareGroup.create! valid_attributes
      expect {
        delete software_group_url(software_group)
      }.to change(SoftwareGroup, :count).by(-1)
    end

    it "redirects to the software_groups list" do
      software_group = SoftwareGroup.create! valid_attributes
      delete software_group_url(software_group)
      expect(response).to redirect_to(software_groups_url)
    end
  end
end
