@startuml
!theme mirco from ../../../../..

agent client [
  Client  
]

rectangle proxy [
    Reverse Proxy
]

rectangle mirco #lightgreen [
  Mirco
]

client --> "https://myhost.example.com\nwss://myhost.example.com/cable" proxy

proxy --> "http://localhost:3001\nws://localhost:3001/cable" mirco

@enduml