@startuml
top to bottom direction
skinparam defaultTextAlignment center
skinparam roundCorner 15

class Server  {
  name: string
  uid: string
  location: string
  description: text
  api_url: string
  api_user: string
  api_password_ciphertext: text
  api_user_has_full_access: boolean
  api_verify_ssl: boolean
  properties: jsonb
  last_channel_update: timestamp
  last_check: timestamp
  last_check_ok: timestamp
}

class Channel {
  uid: string
  properties: jsonb
}

class ChannelStatistic {
  server_id
  channel_id
  server_uid: string
  channel_uid: string
  meta_data_id: integer
  received: integer
  sent: integer
  error: integer
  filtered: integer
  queued: integer
}

class ChannelCounter {
  channel_id
  server_id
  meta_data_id: integer
  received: integer
  sent: integer
  error: integer
  filtered: integer
  queued: integer
}

class Alert {
  channel_id
  server_id
  type: string : alert, recovery
  message: text
}

class Note {
  channel_id
  server_id
  user_id
  type: string : ack, mail
}

Server "1" -- "*" Channel
Server "1" - "*" ChannelStatistic
Channel "1" - "1" ChannelStatistic
ChannelCounter "*" - "1" Server
ChannelCounter "*" -- "1" Channel
Server "1" -- "*" Alert
Channel "0..1" -- "*" Alert
Server "1" -- "*" Note
Channel "0..1" -- "*" Note


@enduml
