
@startuml

' Channel Tx_to_ORGACARD
' Definitions
queue ch_5 as "Tx_to_ORGACARD"
interface ch_5_src as "Channel Reader"

rectangle ch_5_dst_1 as "tcp://172.17.35.164:5555"
rectangle ch_5_dst_3 as "tcp://172.17.35.164:5555"

' Graphs
ch_5_src --> ch_5

ch_5 --> "1" ch_5_dst_1
ch_5 --> "3" ch_5_dst_3

@enduml
