# Mirco config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  # url: <%= ENV.fetch('MIRCO_DATABASE_URL') { "postgres://postgres:postgres@localhost/mirco_production" } %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5).to_i + ENV.fetch("GOOD_JOB_MAX_THREADS", 4).to_i %>

development: &development
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { "mirco_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { "mirco_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { "mirco_production" } %>
