= Podman in production using systemd and quadlets
:navtitle: production: systemd + quadlets
:author: Wolfgang Barth
:revdate: 2024-07-16
:imagesdir: ../../images

== Requirements

* podman Version >= 4.4, better 4.6 or higher.

If something doesn't work have a look at https://docs.podman.io/en/stable/markdown/podman-systemd.unit.5.html and select your podman version (right bottom corner).

.Podman Version in some linux distributions
[cols="2,2,3"]
|===
|Distro | Version | usable?

|Fedora 38    |4.7.2 |ok
|Fedora 39    |4.8.1 |ok
|Fedora 40    |5.1.1 |ok
|Ubuntu 23.10 |4.3.1 |doesn't work
|Ubuntu 24.04 |4.7.2 |ok
|===

== Overview

image::podman/mirco-quadlets.svg[]

NOTE: To run rootless containers, first create a special user. Say our user is 
`poddy` and has uid 1001.

.Rootless setup: directories and files
[subs="+macros"]
----
/etc/containers/systemd/users/1001/mirco
├── xref:attachment$podman/quadlet/env.production[env.production]
├── xref:attachment$podman/quadlet/mirco.yml[mirco.yml]
├── xref:attachment$podman/quadlet/mirco.container[mirco.container]
├── xref:attachment$podman/quadlet/mirco.network[mirco.network]
├── xref:attachment$podman/quadlet/mirco-postgres.container[mirco-postgres.container]
├── xref:attachment$podman/quadlet/mirco-postgres.volume[mirco-postgres.volume]
├── xref:attachment$podman/quadlet/mirco-redis.container[mirco-redis.container]
├── xref:attachment$podman/quadlet/mirco-redis.volume[mirco-redis.volume]
├── xref:attachment$podman/quadlet/mirco-storage.volume[mirco-storage.volume]
├── xref:attachment$podman/quadlet/mirco-tmp.volume[mirco-tmp.volume]
└── xref:attachment$podman/quadlet/mirco-worker-container[mirco-worker.container]
----

== How to run rootless containers with podman

You need to enable linger, otherwise your containers will stop running after you log out.

.Enable linger for poddy
[source,sh]
----
loginctl enable-linger poddy
----
If you use sudo or su to become poddy, two environment variables should be 
checked/set after becoming `poddy`:

.Set environment variables
[source,sh]
----
export XDG_RUNTIME_DIR="/run/user/1001"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
----

.Create the neccessary systemd directory
[source,sh]
----
mkdir -p /etc/containers/systemd/users/1001/mirco
chown -R poddy:poddy /etc/containers/systemd/users/1001
chmod 700 -R /etc/containers/systemd/users/1001
----

Now copy all the files from above to 
`/etc/containers/systemd/users/1001/mirco`.

IMPORTANT: Now is a good time to create your own credentials and update env.production!

.(user poddy) Reload systemd
[source,sh]
----
systemctl --user daemon-reload
----

.(user poddy) Start postgresql first - wait - start the rest
[source,sh]
----
systemctl --user start mirco-postgres
...
systemctl --user start mirco
----

.(user poddy) Check logs
----
# complete output
journalctl --user -f
...
# specific to one container
journalctl --user -u mirco -f
----

== Resources

* https://www.redhat.com/sysadmin/quadlet-podman
* https://www.redhat.com/sysadmin/multi-container-application-podman-quadlet
* https://docs.podman.io/en/stable/markdown/podman-systemd.unit.5.html
* https://github.com/swobspace/ansible-role-podman