require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/escalation_times", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EscalationTime. As you add validations to EscalationTime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EscalationTime.create! valid_attributes
      get escalation_times_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      escalation_time = EscalationTime.create! valid_attributes
      get escalation_time_url(escalation_time)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_escalation_time_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      escalation_time = EscalationTime.create! valid_attributes
      get edit_escalation_time_url(escalation_time)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EscalationTime" do
        expect {
          post escalation_times_url, params: { escalation_time: valid_attributes }
        }.to change(EscalationTime, :count).by(1)
      end

      it "redirects to the created escalation_time" do
        post escalation_times_url, params: { escalation_time: valid_attributes }
        expect(response).to redirect_to(escalation_time_url(EscalationTime.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EscalationTime" do
        expect {
          post escalation_times_url, params: { escalation_time: invalid_attributes }
        }.to change(EscalationTime, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post escalation_times_url, params: { escalation_time: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested escalation_time" do
        escalation_time = EscalationTime.create! valid_attributes
        patch escalation_time_url(escalation_time), params: { escalation_time: new_attributes }
        escalation_time.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the escalation_time" do
        escalation_time = EscalationTime.create! valid_attributes
        patch escalation_time_url(escalation_time), params: { escalation_time: new_attributes }
        escalation_time.reload
        expect(response).to redirect_to(escalation_time_url(escalation_time))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        escalation_time = EscalationTime.create! valid_attributes
        patch escalation_time_url(escalation_time), params: { escalation_time: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested escalation_time" do
      escalation_time = EscalationTime.create! valid_attributes
      expect {
        delete escalation_time_url(escalation_time)
      }.to change(EscalationTime, :count).by(-1)
    end

    it "redirects to the escalation_times list" do
      escalation_time = EscalationTime.create! valid_attributes
      delete escalation_time_url(escalation_time)
      expect(response).to redirect_to(escalation_times_url)
    end
  end
end
